using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace BudgetClasses
{
    public enum CurrencyType : ushort
    {
        AED = 784,
        AFN = 971,
        ALL = 8,
        AMD = 51,
        ANG = 532,
        AOA = 973,
        ARS = 32,
        AUD = 36,
        AWG = 533,
        AZN = 944,
        BAM = 977,
        BBD = 52,
        BDT = 50,
        BGN = 975,
        BHD = 48,
        BIF = 108,
        BMD = 60,
        BND = 96,
        BOB = 68,
        BOV = 984,
        BRL = 986,
        BSD = 44,
        BTN = 64,
        BWP = 72,
        BYR = 974,
        BZD = 84,
        CAD = 124,
        CDF = 976,
        CHE = 947,
        CHF = 756,
        CHW = 948,
        CLF = 990,
        CLP = 152,
        CNY = 156,
        COP = 170,
        COU = 970,
        CRC = 188,
        CUC = 931,
        CUP = 192,
        CVE = 132,
        CZK = 203,
        DJF = 262,
        DKK = 208,
        DOP = 214,
        DZD = 12,
        EGP = 818,
        ERN = 232,
        ETB = 230,
        EUR = 978,
        FJD = 242,
        FKP = 238,
        GBP = 826,
        GEL = 981,
        GHS = 936,
        GIP = 292,
        GMD = 270,
        GNF = 324,
        GTQ = 320,
        GYD = 328,
        HKD = 344,
        HNL = 340,
        HRK = 191,
        HTG = 332,
        HUF = 348,
        IDR = 360,
        ILS = 376,
        INR = 356,
        IQD = 368,
        IRR = 364,
        ISK = 352,
        JMD = 388,
        JOD = 400,
        JPY = 392,
        KES = 404,
        KGS = 417,
        KHR = 116,
        KMF = 174,
        KPW = 408,
        KRW = 410,
        KWD = 414,
        KYD = 136,
        KZT = 398,
        LAK = 418,
        LBP = 422,
        LKR = 144,
        LRD = 430,
        LSL = 426,
        LYD = 434,
        MAD = 504,
        MDL = 498,
        MGA = 969,
        MKD = 807,
        MMK = 104,
        MNT = 496,
        MOP = 446,
        MRO = 478,
        MUR = 480,
        MVR = 462,
        MWK = 454,
        MXN = 484,
        MXV = 979,
        MYR = 458,
        MZN = 943,
        NAD = 516,
        NGN = 566,
        NIO = 558,
        NOK = 578,
        NPR = 524,
        NZD = 554,
        OMR = 512,
        PAB = 590,
        PEN = 604,
        PGK = 598,
        PHP = 608,
        PKR = 586,
        PLN = 985,
        PYG = 600,
        QAR = 634,
        RON = 946,
        RSD = 941,
        RUB = 643,
        RWF = 646,
        SAR = 682,
        SBD = 90,
        SCR = 690,
        SDG = 938,
        SEK = 752,
        SGD = 702,
        SHP = 654,
        SLL = 694,
        SOS = 706,
        SRD = 968,
        SSP = 728,
        STD = 678,
        SYP = 760,
        SZL = 748,
        THB = 764,
        TJS = 972,
        TMT = 934,
        TND = 788,
        TOP = 776,
        TRY = 949,
        TTD = 780,
        TWD = 901,
        TZS = 834,
        UAH = 980,
        UGX = 800,
        USD = 840,
        USN = 997,
        USS = 998,
        UYI = 940,
        UYU = 858,
        UZS = 860,
        VEF = 937,
        VND = 704,
        VUV = 548,
        WST = 882,
        XAF = 950,
        XAG = 961,
        XAU = 959,
        XCD = 951,
        XOF = 952,
        XXX = 999,
        XPF = 953,
        YER = 886,
        ZAR = 710,
        ZMW = 967
    }

    public static class CurrencyTypeExtensions
    {
        #region Dictionaries
        private static Dictionary<CurrencyType, string> CurrencyFullNames = new Dictionary<CurrencyType, string>()
        {
            {CurrencyType.AED, "United Arab Emirates dirham"},
            {CurrencyType.AFN, "Afghan afghani"},
            {CurrencyType.ALL, "Albanian lek"},
            {CurrencyType.AMD, "Armenian dram"},
            {CurrencyType.ANG, "Netherlands Antillean guilder"},
            {CurrencyType.AOA, "Angolan kwanza"},
            {CurrencyType.ARS, "Argentine peso"},
            {CurrencyType.AUD, "Australian dollar"},
            {CurrencyType.AWG, "Aruban florin"},
            {CurrencyType.AZN, "Azerbaijani manat"},
            {CurrencyType.BAM, "Bosnia and Herzegovina convertible mark"},
            {CurrencyType.BBD, "Barbados dollar"},
            {CurrencyType.BDT, "Bangladeshi taka"},
            {CurrencyType.BGN, "Bulgarian lev"},
            {CurrencyType.BHD, "Bahraini dinar"},
            {CurrencyType.BIF, "Burundian franc"},
            {CurrencyType.BMD, "Bermudian dollar"},
            {CurrencyType.BND, "Brunei dollar"},
            {CurrencyType.BOB, "Boliviano"},
            {CurrencyType.BOV, "Bolivian Mvdol (funds code)"},
            {CurrencyType.BRL, "Brazilian real"},
            {CurrencyType.BSD, "Bahamian dollar"},
            {CurrencyType.BTN, "Bhutanese ngultrum"},
            {CurrencyType.BWP, "Botswana pula"},
            {CurrencyType.BYR, "Belarusian ruble"},
            {CurrencyType.BZD, "Belize dollar"},
            {CurrencyType.CAD, "Canadian dollar"},
            {CurrencyType.CDF, "Congolese franc"},
            {CurrencyType.CHE, "WIR Euro (complementary currency)"},
            {CurrencyType.CHF, "Swiss franc"},
            {CurrencyType.CHW, "WIR Franc (complementary currency)"},
            {CurrencyType.CLF, "Unidad de Fomento (funds code)"},
            {CurrencyType.CLP, "Chilean peso"},
            {CurrencyType.CNY, "Chinese yuan"},
            {CurrencyType.COP, "Colombian peso"},
            {CurrencyType.COU, "Unidad de Valor Real (UVR) (funds code)[7]"},
            {CurrencyType.CRC, "Costa Rican colon"},
            {CurrencyType.CUC, "Cuban convertible peso"},
            {CurrencyType.CUP, "Cuban peso"},
            {CurrencyType.CVE, "Cape Verde escudo"},
            {CurrencyType.CZK, "Czech koruna"},
            {CurrencyType.DJF, "Djiboutian franc"},
            {CurrencyType.DKK, "Danish krone"},
            {CurrencyType.DOP, "Dominican peso"},
            {CurrencyType.DZD, "Algerian dinar"},
            {CurrencyType.EGP, "Egyptian pound"},
            {CurrencyType.ERN, "Eritrean nakfa"},
            {CurrencyType.ETB, "Ethiopian birr"},
            {CurrencyType.EUR, "Euro"},
            {CurrencyType.FJD, "Fiji dollar"},
            {CurrencyType.FKP, "Falkland Islands pound"},
            {CurrencyType.GBP, "Pound sterling"},
            {CurrencyType.GEL, "Georgian lari"},
            {CurrencyType.GHS, "Ghanaian cedi"},
            {CurrencyType.GIP, "Gibraltar pound"},
            {CurrencyType.GMD, "Gambian dalasi"},
            {CurrencyType.GNF, "Guinean franc"},
            {CurrencyType.GTQ, "Guatemalan quetzal"},
            {CurrencyType.GYD, "Guyanese dollar"},
            {CurrencyType.HKD, "Hong Kong dollar"},
            {CurrencyType.HNL, "Honduran lempira"},
            {CurrencyType.HRK, "Croatian kuna"},
            {CurrencyType.HTG, "Haitian gourde"},
            {CurrencyType.HUF, "Hungarian forint"},
            {CurrencyType.IDR, "Indonesian rupiah"},
            {CurrencyType.ILS, "Israeli new shekel"},
            {CurrencyType.INR, "Indian rupee"},
            {CurrencyType.IQD, "Iraqi dinar"},
            {CurrencyType.IRR, "Iranian rial"},
            {CurrencyType.ISK, "Icelandic króna"},
            {CurrencyType.JMD, "Jamaican dollar"},
            {CurrencyType.JOD, "Jordanian dinar"},
            {CurrencyType.JPY, "Japanese yen"},
            {CurrencyType.KES, "Kenyan shilling"},
            {CurrencyType.KGS, "Kyrgyzstani som"},
            {CurrencyType.KHR, "Cambodian riel"},
            {CurrencyType.KMF, "Comoro franc"},
            {CurrencyType.KPW, "North Korean won"},
            {CurrencyType.KRW, "South Korean won"},
            {CurrencyType.KWD, "Kuwaiti dinar"},
            {CurrencyType.KYD, "Cayman Islands dollar"},
            {CurrencyType.KZT, "Kazakhstani tenge"},
            {CurrencyType.LAK, "Lao kip"},
            {CurrencyType.LBP, "Lebanese pound"},
            {CurrencyType.LKR, "Sri Lankan rupee"},
            {CurrencyType.LRD, "Liberian dollar"},
            {CurrencyType.LSL, "Lesotho loti"},
            {CurrencyType.LYD, "Libyan dinar"},
            {CurrencyType.MAD, "Moroccan dirham"},
            {CurrencyType.MDL, "Moldovan leu"},
            {CurrencyType.MGA, "Malagasy ariary"},
            {CurrencyType.MKD, "Macedonian denar"},
            {CurrencyType.MMK, "Myanmar kyat"},
            {CurrencyType.MNT, "Mongolian tugrik"},
            {CurrencyType.MOP, "Macanese pataca"},
            {CurrencyType.MRO, "Mauritanian ouguiya"},
            {CurrencyType.MUR, "Mauritian rupee"},
            {CurrencyType.MVR, "Maldivian rufiyaa"},
            {CurrencyType.MWK, "Malawian kwacha"},
            {CurrencyType.MXN, "Mexican peso"},
            {CurrencyType.MXV, "Mexican Unidad de Inversion (UDI) (funds code)"},
            {CurrencyType.MYR, "Malaysian ringgit"},
            {CurrencyType.MZN, "Mozambican metical"},
            {CurrencyType.NAD, "Namibian dollar"},
            {CurrencyType.NGN, "Nigerian naira"},
            {CurrencyType.NIO, "Nicaraguan córdoba"},
            {CurrencyType.NOK, "Norwegian krone"},
            {CurrencyType.NPR, "Nepalese rupee"},
            {CurrencyType.NZD, "New Zealand dollar"},
            {CurrencyType.OMR, "Omani rial"},
            {CurrencyType.PAB, "Panamanian balboa"},
            {CurrencyType.PEN, "Peruvian nuevo sol"},
            {CurrencyType.PGK, "Papua New Guinean kina"},
            {CurrencyType.PHP, "Philippine peso"},
            {CurrencyType.PKR, "Pakistani rupee"},
            {CurrencyType.PLN, "Polish zloty"},
            {CurrencyType.PYG, "Paraguayan guaraní"},
            {CurrencyType.QAR, "Qatari riyal"},
            {CurrencyType.RON, "Romanian leu"},
            {CurrencyType.RSD, "Serbian dinar"},
            {CurrencyType.RUB, "Russian ruble"},
            {CurrencyType.RWF, "Rwandan franc"},
            {CurrencyType.SAR, "Saudi riyal"},
            {CurrencyType.SBD, "Solomon Islands dollar"},
            {CurrencyType.SCR, "Seychelles rupee"},
            {CurrencyType.SDG, "Sudanese pound"},
            {CurrencyType.SEK, "Swedish krona/kronor"},
            {CurrencyType.SGD, "Singapore dollar"},
            {CurrencyType.SHP, "Saint Helena pound"},
            {CurrencyType.SLL, "Sierra Leonean leone"},
            {CurrencyType.SOS, "Somali shilling"},
            {CurrencyType.SRD, "Surinamese dollar"},
            {CurrencyType.SSP, "South Sudanese pound"},
            {CurrencyType.STD, "São Tomé and Príncipe dobra"},
            {CurrencyType.SYP, "Syrian pound"},
            {CurrencyType.SZL, "Swazi lilangeni"},
            {CurrencyType.THB, "Thai baht"},
            {CurrencyType.TJS, "Tajikistani somoni"},
            {CurrencyType.TMT, "Turkmenistani manat"},
            {CurrencyType.TND, "Tunisian dinar"},
            {CurrencyType.TOP, "Tongan pa?anga"},
            {CurrencyType.TRY, "Turkish lira"},
            {CurrencyType.TTD, "Trinidad and Tobago dollar"},
            {CurrencyType.TWD, "New Taiwan dollar"},
            {CurrencyType.TZS, "Tanzanian shilling"},
            {CurrencyType.UAH, "Ukrainian hryvnia"},
            {CurrencyType.UGX, "Ugandan shilling"},
            {CurrencyType.USD, "United States dollar"},
            {CurrencyType.USN, "United States dollar (next day) (funds code)"},
            {CurrencyType.USS, "United States dollar (same day) (funds code)[10]"},
            {CurrencyType.UYI, "Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)"},
            {CurrencyType.UYU, "Uruguayan peso"},
            {CurrencyType.UZS, "Uzbekistan som"},
            {CurrencyType.VEF, "Venezuelan bolívar"},
            {CurrencyType.VND, "Vietnamese dong"},
            {CurrencyType.VUV, "Vanuatu vatu"},
            {CurrencyType.WST, "Samoan tala"},
            {CurrencyType.XAF, "CFA franc BEAC"},
            {CurrencyType.XAG, "Silver (one troy ounce)"},
            {CurrencyType.XAU, "Gold (one troy ounce)"},
            {CurrencyType.XCD, "East Caribbean dollar"},
            {CurrencyType.XOF, "CFA franc BCEAO"},
            {CurrencyType.XPF, "CFP franc (franc Pacifique)"},
            {CurrencyType.XXX, "No currency"},
            {CurrencyType.YER, "Yemeni rial"},
            {CurrencyType.ZAR, "South African rand"},
            {CurrencyType.ZMW, "Zambian kwacha"}
        };

        private static Dictionary<CurrencyType, int> CurrencyDenominators = new Dictionary<CurrencyType, int>()
        {
            {CurrencyType.AED, 100},
            {CurrencyType.AFN, 100},
            {CurrencyType.ALL, 100},
            {CurrencyType.AMD, 100},
            {CurrencyType.ANG, 100},
            {CurrencyType.AOA, 100},
            {CurrencyType.ARS, 100},
            {CurrencyType.AUD, 100},
            {CurrencyType.AWG, 100},
            {CurrencyType.AZN, 100},
            {CurrencyType.BAM, 100},
            {CurrencyType.BBD, 100},
            {CurrencyType.BDT, 100},
            {CurrencyType.BGN, 100},
            {CurrencyType.BHD, 1000},
            {CurrencyType.BIF, 1},
            {CurrencyType.BMD, 100},
            {CurrencyType.BND, 100},
            {CurrencyType.BOB, 100},
            {CurrencyType.BOV, 100},
            {CurrencyType.BRL, 100},
            {CurrencyType.BSD, 100},
            {CurrencyType.BTN, 100},
            {CurrencyType.BWP, 100},
            {CurrencyType.BYR, 1},
            {CurrencyType.BZD, 100},
            {CurrencyType.CAD, 100},
            {CurrencyType.CDF, 100},
            {CurrencyType.CHE, 100},
            {CurrencyType.CHF, 100},
            {CurrencyType.CHW, 100},
            {CurrencyType.CLF, 10000},
            {CurrencyType.CLP, 1},
            {CurrencyType.CNY, 100},
            {CurrencyType.COP, 100},
            {CurrencyType.COU, 100},
            {CurrencyType.CRC, 100},
            {CurrencyType.CUC, 100},
            {CurrencyType.CUP, 100},
            {CurrencyType.CVE, 1},
            {CurrencyType.CZK, 100},
            {CurrencyType.DJF, 1},
            {CurrencyType.DKK, 100},
            {CurrencyType.DOP, 100},
            {CurrencyType.DZD, 100},
            {CurrencyType.EGP, 100},
            {CurrencyType.ERN, 100},
            {CurrencyType.ETB, 100},
            {CurrencyType.EUR, 100},
            {CurrencyType.FJD, 100},
            {CurrencyType.FKP, 100},
            {CurrencyType.GBP, 100},
            {CurrencyType.GEL, 100},
            {CurrencyType.GHS, 100},
            {CurrencyType.GIP, 100},
            {CurrencyType.GMD, 100},
            {CurrencyType.GNF, 1},
            {CurrencyType.GTQ, 100},
            {CurrencyType.GYD, 100},
            {CurrencyType.HKD, 100},
            {CurrencyType.HNL, 100},
            {CurrencyType.HRK, 100},
            {CurrencyType.HTG, 100},
            {CurrencyType.HUF, 100},
            {CurrencyType.IDR, 100},
            {CurrencyType.ILS, 100},
            {CurrencyType.INR, 100},
            {CurrencyType.IQD, 1000},
            {CurrencyType.IRR, 100},
            {CurrencyType.ISK, 1},
            {CurrencyType.JMD, 100},
            {CurrencyType.JOD, 1000},
            {CurrencyType.JPY, 1},
            {CurrencyType.KES, 100},
            {CurrencyType.KGS, 100},
            {CurrencyType.KHR, 100},
            {CurrencyType.KMF, 1},
            {CurrencyType.KPW, 100},
            {CurrencyType.KRW, 1},
            {CurrencyType.KWD, 1000},
            {CurrencyType.KYD, 100},
            {CurrencyType.KZT, 100},
            {CurrencyType.LAK, 100},
            {CurrencyType.LBP, 100},
            {CurrencyType.LKR, 100},
            {CurrencyType.LRD, 100},
            {CurrencyType.LSL, 100},
            {CurrencyType.LYD, 1000},
            {CurrencyType.MAD, 100},
            {CurrencyType.MDL, 100},
            {CurrencyType.MGA, 10},
            {CurrencyType.MKD, 100},
            {CurrencyType.MMK, 100},
            {CurrencyType.MNT, 100},
            {CurrencyType.MOP, 100},
            {CurrencyType.MRO, 10},
            {CurrencyType.MUR, 100},
            {CurrencyType.MVR, 100},
            {CurrencyType.MWK, 100},
            {CurrencyType.MXN, 100},
            {CurrencyType.MXV, 100},
            {CurrencyType.MYR, 100},
            {CurrencyType.MZN, 100},
            {CurrencyType.NAD, 100},
            {CurrencyType.NGN, 100},
            {CurrencyType.NIO, 100},
            {CurrencyType.NOK, 100},
            {CurrencyType.NPR, 100},
            {CurrencyType.NZD, 100},
            {CurrencyType.OMR, 1000},
            {CurrencyType.PAB, 100},
            {CurrencyType.PEN, 100},
            {CurrencyType.PGK, 100},
            {CurrencyType.PHP, 100},
            {CurrencyType.PKR, 100},
            {CurrencyType.PLN, 100},
            {CurrencyType.PYG, 1},
            {CurrencyType.QAR, 100},
            {CurrencyType.RON, 100},
            {CurrencyType.RSD, 100},
            {CurrencyType.RUB, 100},
            {CurrencyType.RWF, 1},
            {CurrencyType.SAR, 100},
            {CurrencyType.SBD, 100},
            {CurrencyType.SCR, 100},
            {CurrencyType.SDG, 100},
            {CurrencyType.SEK, 100},
            {CurrencyType.SGD, 100},
            {CurrencyType.SHP, 100},
            {CurrencyType.SLL, 100},
            {CurrencyType.SOS, 100},
            {CurrencyType.SRD, 100},
            {CurrencyType.SSP, 100},
            {CurrencyType.STD, 100},
            {CurrencyType.SYP, 100},
            {CurrencyType.SZL, 100},
            {CurrencyType.THB, 100},
            {CurrencyType.TJS, 100},
            {CurrencyType.TMT, 100},
            {CurrencyType.TND, 1000},
            {CurrencyType.TOP, 100},
            {CurrencyType.TRY, 100},
            {CurrencyType.TTD, 100},
            {CurrencyType.TWD, 100},
            {CurrencyType.TZS, 100},
            {CurrencyType.UAH, 100},
            {CurrencyType.UGX, 1},
            {CurrencyType.USD, 100},
            {CurrencyType.USN, 100},
            {CurrencyType.USS, 100},
            {CurrencyType.UYI, 1},
            {CurrencyType.UYU, 100},
            {CurrencyType.UZS, 100},
            {CurrencyType.VEF, 100},
            {CurrencyType.VND, 1},
            {CurrencyType.VUV, 1},
            {CurrencyType.WST, 100},
            {CurrencyType.XAF, 1},
            {CurrencyType.XAG, 1},
            {CurrencyType.XAU, 1},
            {CurrencyType.XCD, 100},
            {CurrencyType.XOF, 1},
            {CurrencyType.XPF, 1},
            {CurrencyType.XXX, 1},
            {CurrencyType.YER, 100},
            {CurrencyType.ZAR, 100},
            {CurrencyType.ZMW, 100}
        };

        #endregion

        public static string FullName(this CurrencyType self)
        {
            return CurrencyFullNames[self]; // throws exception if it's not in the dictionary, which is fine.
        }

        public static int Denominator(this CurrencyType self)
        {
            return CurrencyDenominators[self]; // throws exception if it's not in the dictionary, which is fine.
        }
    }
}
